apiVersion: v1
data:
  config.ini: |-
    [OUTPUT]
    path = {{ .Values.output.path }}

    [LOCATION]
    latitude={{ .Values.location.latitude }}
    longitude={{ .Values.location.longitude }}
kind: ConfigMap
metadata:
  name: config