apiVersion: v1
data:
  config.ini: |-
    [OUTPUT]
    path = {{ .Values.output.path }}

    [LOCATION]
    forecast_office_id={{ .Values.location.office }}
    x_coordinate={{ .Values.location.longitude }}
    y_coordinate={{ .Values.location.latitude }}
kind: ConfigMap
metadata:
  name: config