apiVersion: v1
kind: Pod
metadata:
  labels:
    app: fileserver
  name: fileserver
spec:
  containers:
  - image: caddy:2.7.6
    name: webserver
    command:
      - caddy
    args:
      - file-server 
      - --root 
      - /var/www
      - --browse
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: forecast-claim
      mountPath: /var/www
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name : forecast-claim
    persistentVolumeClaim:
      claimName: forecast-claim
