apiVersion: v2
name: argocd-helm
description: Chart for deploying Argo Workflows
type: application
version: 0.1.0
appVersion: "v3.5.6"
dependencies:
  - name: argo-workflows
    repository: https://argoproj.github.io/argo-helm
    version: 0.41.2