---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: l2-announcement
  annotations:
    "helm.sh/hook": post-install
spec:
  blocks:
  - start: {{ .Values.ipRange.start }}
    stop: {{ .Values.ipRange.end }}

