image: 
  registry:  gitea.gc.home.arpa
  repository: black_sage/angi-data-platform-infrastructure-engineer/angi-forecast
  tag: 0.0.1

schedule: "2 * * * *" 
output:
  path: /mnt/pv

location:
  office: TOP
  longitude: 32
  latitude: 81 